### ISSUE TITLE
Not able to save int values . Only binary strings accepted

### ISSUE THREAD

**Issue by silviucpp** [AdRoll/mero#9]
Hello,

how I can add numbers not only binary strings as value ?

**Comment by zerth** [comment]
Please provide a minimal example if this is still an issue for you.

**Comment by silviucpp** [comment]
```
mero:set(default, <<"key">>, 5, 3600, 5000).
```

Silviu

**Comment by zerth** [comment]
Mero doesn't handle the application-level decision of how to encode values to be stored/read from memcache, so this is not an unexpected outcome as far as mero is concerned.
